// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnL6Dq4K659evnpk-6hYX8QaBnLRQmMw',
    appId: '1:788342631343:web:418393ae03edb3e89a5d5a',
    messagingSenderId: '788342631343',
    projectId: 'tryproject-flutter-project',
    authDomain: 'tryproject-flutter-project.firebaseapp.com',
    storageBucket: 'tryproject-flutter-project.appspot.com',
    measurementId: 'G-PT09VS8GS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABdlbQy7hKBCieVxH-1qmBIpqYysAqpTQ',
    appId: '1:788342631343:android:b4c0b663dd7b3f229a5d5a',
    messagingSenderId: '788342631343',
    projectId: 'tryproject-flutter-project',
    storageBucket: 'tryproject-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqAAJsr6N3IryVKxZtU5JZ2hvEDYHd8g',
    appId: '1:788342631343:ios:4e9507d71d74a6579a5d5a',
    messagingSenderId: '788342631343',
    projectId: 'tryproject-flutter-project',
    storageBucket: 'tryproject-flutter-project.appspot.com',
    iosClientId: '788342631343-qslt74h3sc6nlco4l7l2vj09cjtlf3e1.apps.googleusercontent.com',
    iosBundleId: 'com.firstproject.tryproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIqAAJsr6N3IryVKxZtU5JZ2hvEDYHd8g',
    appId: '1:788342631343:ios:4e9507d71d74a6579a5d5a',
    messagingSenderId: '788342631343',
    projectId: 'tryproject-flutter-project',
    storageBucket: 'tryproject-flutter-project.appspot.com',
    iosClientId: '788342631343-qslt74h3sc6nlco4l7l2vj09cjtlf3e1.apps.googleusercontent.com',
    iosBundleId: 'com.firstproject.tryproject',
  );
}
